ros2_api:
  ros__parameters:
    states_topic: "/joint_states" # Where to read this topic. Optional. Default: ... (Message is always all five arrays)
    publishers: # At least one required! 
      - publisher: "JointTrajectoryController" # One of JointTrajectoryController, JointGroupEffortController, JointGroupPositionController, JointGroupVelocityController, ...
        name: "joint_trajectory_controller" #Required!
        #topic: "/..." # Defaults to <name>/joint_trajectory 
      - publisher: "JointGroupEffortController"
        name: "effort"
        #topic: "/..." # Defaults to <name>/commands  
      - publisher: "JointGroupPositionController"  
        name: "position" 
        #topic: "/..." # Defaults to <name>/commands
      - publisher: "JointGroupVelocityController"
        name: "velocity"  
        topic: "/vel_cmds"   
    transport:
      type: "protocols::UnixDomainSocket" # Name of the plugin as set in the pluginlib.xml
      params: # Your own params for the plugin specified. Not checked by parser. Passed to the plugin. Optional.
        socket_path_recv: "/tmp/ros2_api_recv.socket"
        socket_path_send: "/tmp/ros2_api_send.socket"
